services:
  next-app:
    container_name: console
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3471:3471
    restart: always
    networks:
      - dataherald_network
networks:
  dataherald_network:
    external: true
