services:
  next-app:
    container_name: fpa-portal
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    # volumes:
      # - ./:/app
      # - /app/node_modules
      # - /app/.next
    ports:
      - "3461:3461"
    restart: always
    networks:
      - dataherald_network

networks:
  dataherald_network:
    external: true